### ISSUE TITLE
Make proposal action buttons more visible

### ISSUE THREAD

**Issue by brortao** [HughMcGrade/eusay#59]
I think a large part of why we don't see more sabb responses is that the proposal action buttons are hidden by default and are only accessible through a small (and quite unintuitive) button.

Perhaps the original proposal and sabbs should see a big "write official response" button next to the voting buttons? @HughMcGrade, what do you think?

**Comment by brortao** [comment]
Another question: should we call it "write official response" or "update proposal status" or something else?

**Comment by HughMcGrade** [comment]
I've pretty much done this on release-0.2.0 https://github.com/HughMcGrade/eusay/issues/56

**Comment by brortao** [comment]
I somehow missed that. Oops!
