### ISSUE TITLE
Require authentication to report content and make all reports anonymous

### ISSUE THREAD

**Issue by brortao** [HughMcGrade/eusay#62]
Right now, anyone can report content which leads to outside sites spamming the report function. We should require EASE authentication to avoid this.

@HughMcGrade, do you agree?

**Comment by HughMcGrade** [comment]
Yes, that makes sense. This would mean anonymous reports would no longer be possible. We could change it to just make all reports anonymous?

**Comment by brortao** [comment]
Yes, I think that's the best option! Just yesterday we had over 10 spam reports.

On February 9, 2015 11:10:05 AM GMT, Hugh McGrade <notifications@github.com> wrote:
>Yes, that makes sense. This would mean anonymous reports would no
>longer be possible. We could change it to just make all reports
>anonymous?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/HughMcGrade/eusay/issues/62#issuecomment-73492122

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
